### ISSUE TITLE
Get glideobject as JSON

### ISSUE THREAD

**Issue by iamkalai** [iamkalai/SNTIL#106]
Use the following script to get the gliderecord object as JSON
```javascript
var gr = new GlideRecord("u_test_table");
gr.addEncodedQuery("u_message=t1");
gr.query();
if (gr.next()) {
    var fields = new global.GlideRecordUtil().getFields(gr);
    gs.info(JSON.stringify(new SCJSONUtil().getCurrentRecordJSON(gr, fields)));
}
```

**Comment by t1mb0b** [comment]
Question on this one- on some instances, the SCJSONUtil() class does not exist. Is this installed from some specific plugin?

**Comment by iamkalai** [comment]
> Question on this one- on some instances, the SCJSONUtil() class does not exist. Is this installed from some specific plugin?

It seems like part of com.snc.service_charging plugin.

**Comment by t1mb0b** [comment]
> > Question on this one- on some instances, the SCJSONUtil() class does not exist. Is this installed from some specific plugin?
> 
> It seems like part of com.snc.service_charging plugin.

Thank you sir! Would you be willing to share, perhaps in another TIL entry, how you determined that? I generally check the 'File Properties' UI action, and a couple other things, when attempting to determine where an artifact was installed from. I am sure there are a number of ways!

**Comment by iamkalai** [comment]
> > > Question on this one- on some instances, the SCJSONUtil() class does not exist. Is this installed from some specific plugin?
> > 
> > 
> > It seems like part of com.snc.service_charging plugin.
> 
> Thank you sir! Would you be willing to share, perhaps in another TIL entry, how you determined that? I generally check the 'File Properties' UI action, and a couple other things, when attempting to determine where an artifact was installed from. I am sure there are a number of ways!

I use this method - https://github.com/iamkalai/SNTIL/issues/117

**Comment by t1mb0b** [comment]
> > > > Question on this one- on some instances, the SCJSONUtil() class does not exist. Is this installed from some specific plugin?
> > > 
> > > 
> > > It seems like part of com.snc.service_charging plugin.
> > 
> > 
> > Thank you sir! Would you be willing to share, perhaps in another TIL entry, how you determined that? I generally check the 'File Properties' UI action, and a couple other things, when attempting to determine where an artifact was installed from. I am sure there are a number of ways!
> 
> I use this method - #117

Amazing, thank you good sir!
