### ISSUE TITLE
Check if object is OOB and which plugin it belongs.

### ISSUE THREAD

**Issue by iamkalai** [iamkalai/SNTIL#117]
You may or may not know this but if you want to determine if an script or object is OOB, one of the easiest way is checking sys_upgrade_history_log table. You can query the table with condition like filename as tablename_sysid. The table also has a plugin field, which you can use to determine the plugin that added this object.
```javascript
var gr = new GlideRecord("sys_upgrade_history_log");
gr.addEncodedQuery("file_name=sys_script_include_6f320f190bc70300acc30e7363673af8");
gr.setLimit(1);
gr.query();
if (gr.next()) {
    gs.print(gr.getLink());
}
```

**Comment by tylerkfloyd** [comment]
Thanks Kalai! Was wondering how you set this up in the past... A useful check for sure.
