### ISSUE TITLE
getValue() for true/false field

### ISSUE THREAD

**Issue by iamkalai** [iamkalai/SNTIL#66]
Do keep in mind that for true/false field, **getValue()** will return 0 or 1 and not true/false.

```javascript
var gr = new GlideRecord("incident");
gr.addEncodedQuery("number=INC0000002");
gr.query();
if (gr.next()) {
    gs.print("gr.getValue('active') returns: " + gr.getValue('active') + " of type: " + typeof gr.getValue('active'));
    gs.print("gr.active returns: " + gr.active + " of type: " + typeof gr.active);
    gs.print("gr.active.toString() returns: " + gr.active.toString() + " of type: " + typeof gr.active.toString());
    gs.print('(gr.active + "") returns: ' + (gr.active + "") + " of type: " + typeof (gr.active + ""));
}
```

**NOTE**: If a field is unique and we try to update non unique value, no error message is received but the record is not updated. Hence  unique seems to be implemented at DB level

**Comment by n21lv** [comment]
FYI: If you want to get a proper boolean from a GlideRecord, use `global.JSUtil.getBooleanValue(glide_record, field_name)`
