### ISSUE TITLE
Role License

### ISSUE THREAD

**Issue by iamkalai** [iamkalai/SNTIL#85]
You want to know whether a role is licensed or not, go to table "license_role" and check column "Role Type".

**Comment by mskoddow** [comment]
Nice. I suppose you got that tip from [My Linked Post](https://www.linkedin.com/feed/update/urn:li:activity:6885460159875952640/), right?

**Comment by iamkalai** [comment]
> Nice. I suppose you got that tip from [My Linked Post](https://www.linkedin.com/feed/update/urn:li:activity:6885460159875952640/), right?

That is correct. I wasn't aware people were following this board of mine.
